sonar.projectKey=smartalarms-frontend-vue
sonar.projectName=smartalarms-frontend-vue
sonar.projectVersion=1.10.0
sonar.sources=src
sonar.exclusions=**/*.xml,**/*.yml,**/test_*.py,**/*.js
sonar.python.xunit.reportPath=test-report.xml
sonar.python.coverage.reportPath=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.links.homepage=https://smartalarms-dev.transformacaodigitalspassu.com.br:3100
sonar.links.ci=
sonar.links.scm=
sonar.links.issue=https://transformacaodigitalspassu.atlassian.net/secure/RapidBoard.jspa?rapidView%3D29&projectKey%3DSA
