sonar.projectKey=smartalarms-frontend-vue
sonar.projectName=smartalarms-frontend-vue
sonar.projectVersion=1.10.2
sonar.sources=.
sonar.exclusions=**/*.xml,**/*.yml,**/test_*.py,**/*.js, node_modules/**, static/**
sonar.python.xunit.reportPath=test-report.xml
sonar.python.coverage.reportPath=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.links.homepage=https://smartalarms-dev.transformacaodigitalspassu.com.br:3100
sonar.links.ci=https://sa-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/smartalarms-frontend-vue-pipeline-dev/view?region=sa-east-1
sonar.links.scm=https://sa-east-1.console.aws.amazon.com/codesuite/codecommit/repositories/smartalarms-frontend-vue-git/browse/refs/heads/develop?region=sa-east-1
sonar.links.issue=https://transformacaodigitalspassu.atlassian.net/secure/RapidBoard.jspa?rapidView%3D29&projectKey%3DSA
